### ISSUE TITLE
How long does it take to train?

### ISSUE THREAD

**Issue by htwang14** [taeyoungson/urie#3]
Hi, thanks for releasing the codes of your great work! In this repo, the image corruptions seem to be calculated online using CPUs, blocking the pipeline and resulting in low GPU utilization and prolonged training time: The ImageNet experiment with ResNet18 takes 6 hours for 1 epoch on my machine with 4 1080Ti GPUs. Could you please provide your training time and hardware configurations? Thanks in advance!

**Comment by taeyoungson** [comment]
The reason I designed the corruptions to be applied on-the-fly is because of disk capacity.
ImageNet dataset is huge, therefore generating corrupted-version of it takes a tremendous amount of time (19 corruptions * 5 severity * # of images == HUGE)
As far as I can tell, taking 6 hours for 1epoch seems reasonable since it trains on the ImageNet dataset.
In my case, I used 8 RTX2080Ti machines and it took about 3-4 days for training. 
Thanks for having an interest in my work.
